version: '3.8'

services:
  web:
    build: ./project
    container_name: homesite_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: homesite_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  
  celery:
    build: ./project
    container_name: homesite_celery_worker
    command: celery --app=config worker -l INFO
    volumes:
      - ./project:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - rabbitmq
      - web
      
  tailwind:
    build: ./node_staticfiles
    container_name: homesite_tailwind
    command: npm run tailwind
    tty: true
    volumes:
      - ./node_staticfiles:/node
      - ./project:/project
    depends_on:
      - web

  webpack:
    build: ./node_staticfiles
    container_name: homesite_webpack
    command: npm run webpack
    volumes:
      - ./node_staticfiles:/node
      - ./project:/project
    depends_on:
      - web
    
  db:
    image: postgres:14
    container_name: homesite_postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    # ports:
    #   - 5431:5432
volumes:
  postgres_data: