version: '3.8'

services:
  web:
    build:
      context: ./project
      dockerfile: Dockerfile.prod
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
  
  celery:
    build:
      context: ./project
      dockerfile: Dockerfile.prod
    command: celery --app=config worker -l INFO
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - web
  db:
    image: postgres:14
    container_name: homesite_postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - 5431:5432

volumes:
  postgres_data: